update

diff --git a/unused b/unused
--- a/unused
+++ b/unused
@@ -1,149 +1,114 @@
 #!/bin/sh
 
-# Description:
-#     This command is used to identify unused components in a SPA project.
-#     Unused files are written to "unsed.txt" with absolute paths.
-#     It will identify unused components in the following ways:
-#
-#         1. Match any extension of ".js", ".jsx", ".ts", ".tsx" ".astro" ".vue" ".svelte".
-#         2. Matching file is called in the form of "import from".
-#         3. Obtains the characters after "from" and determines if they match the file name.
-#            If the file name is "index", do not include the file.
-#         4. Compare the file directly under the specified directory with the characters after "from".
-#         5. If there is no match, it is assumed to be an unused component.
-#         6. Output to file
-#
 # Usage:
-#     source main.sh [options] <directory-path>
+#
+#     ╭─ Zsh ─────────────────────────────────────────────────────────────────────────────────╮
+#     │  $ unused [options] <directory-path>                                                  │
+#     ╰───────────────────────────────────────────────────────────────────────────────────────╯
 #
 # Options:
-#     -d, --double: using double quotes
-#     -s, --single: using single quotes
-#     -c, --confirm: Turn on confirmation to delete files
-#     -o, --output <file-name>: output to file
-#     -e, --exclude '<file-name> ...': exclude the files
-#     -D, --delete: delete the unused files
+#     -f, --ignore-files '<file-name> ...': exclude the files
+#     -d, --ignore-dirs '<dir-name> ...': exclude the dirs
 #
 # Examples:
-#     $ source main.sh -s -o output.txt ./src
-#     $ source main.sh -s -o output.txt -e "index.js" ./src
 #
-# Warning:
-#     This command does not perfectly output unused files.
-#     The "-D, --delete" option should be avoided if possible.
-#     If you do use it, please use it only in an environment where you can revert deleted files.
+#     ╭─ Zsh ─────────────────────────────────────────────────────────────────────────────────╮
+#     │  $ unused -f "index.svelte app.d.ts" ./src                                            │
+#     │  $ unused -d "routes lib" ./src                                                       │
+#     ╰───────────────────────────────────────────────────────────────────────────────────────╯
 
-NO_COLOR="\033[0m"
+
+RED="\033[0;31m"
 YELLOW="\033[1;33m"
+NO_COLOR="\033[0m"
+CONFIRM=true
+DELETE=true
+DELIMITER="'"
+TARGET_EXTENSIONS=(".jsx" ".tsx" ".astro" ".svelte" ".vue")
+IGNORE_DIRS=("pages")
+IGNORE_FILES=()
 
-# Use single or double quotes, depending on the situation
-delimiter="'"                # Use single quotes by default
-outputFileName="unused.txt"  # default output file name
-confirm=false                # default is not to confirm deletion
-
-IGNORE_FILES=("env.d.ts")    # Ignore files
-IGNORE_DIRS=("pages")        # Ignore directories
 usingModulePaths=()
 targetFilePaths=()
 unusedModulePaths=()
-targetExtensions=(".js" ".jsx" ".ts" ".tsx" ".astro" ".vue" ".svelte")
 
 while [ $# -gt 0 ]; do
-    case "$1" in
-        -d|--double)
-            delimiter="\""
-            ;;
-        -s|--single)
-            delimiter="'"
-            ;;
-        -c|--confirm)
-            confirm=true
-            ;;
-        -o|--output)
-            shift
-            outputFileName="$1"
-            ;;
-        -D|--delete)
-            delete=true
-            ;;
-        -e|--exclude)
-            shift
-            excludeFiles="$1"
-            ;;
-        *)
-            # if no option, assume it is the directory path
-            if [ -z "$directoryPath" ]; then
-                directoryPath="$1"
-            else
-                echo "Invalid option: $1"
-                exit 1
-            fi
-            ;;
-    esac
-    shift
+  case "$1" in
+    -f|--ignore-files)
+      shift
+      excludeFiles="$1"
+      ;;
+    -d|--ignore-dirs)
+      shift
+      excludeDirs="$1"
+      ;;
+    *)
+    # if no option, assume it is the directory path
+    if [ -z "$directoryPath" ]; then
+      directoryPath="$1"
+    else
+      echo "Invalid option: $1"
+      exit 1
+    fi
+    ;;
+  esac
+  shift
 done
 
-excludeFiles=($excludeFiles)
+IGNORE_DIRS+=($excludeDirs)
+IGNORE_FILES+=($excludeFiles)
 
-# Confirmation regarding delete option
-if [ "$delete" = true ]; then
-    echo "Are you sure you want to delete the unused files?"
-    echo "Type 'yes' to continue: "
-    read answer
-    if [ "$answer" != "yes" ]; then
-        echo "Aborting..."
-        exit 1
-    fi
-fi
-
-# Note: To use double quotation marks, rewrite the code as follows
-#     moduleNameRetriver: 2
-#     split($0, splited_line, "'$delimiter'");
-#     split($0, splited_line, "\'$delimiter'");
 moduleNameRetriver='
-BEGIN {
-    FS = "'$delimiter'";
-}
-
 /^(\t| ){1,}import.+from/ {
-    split($0, splited_line, FS);
-    module_path = splited_line[2];
+  split($0, splited_line, "'$DELIMITER'");
+  module_path = splited_line[2];
 
-    split(module_path, splited_module_path, "/");
-    splited_module_path_length = length(splited_module_path);
+  split(module_path, splited_module_path, "/");
+  splited_module_path_length = length(splited_module_path);
 
-    print(splited_module_path[splited_module_path_length]);
+  print(splited_module_path[splited_module_path_length]);
 }
 '
 
 splitter='
 {
-    split($1, arr, "/");
-    arr_length = length(arr);
-    print(arr[arr_length]);
+  split($1, arr, "/");
+  arr_length = length(arr);
+  print(arr[arr_length]);
 }
 '
 
 replacer='
 {
-    gsub(before, after, $0);
-    print(result);
+  split($0, array, file_name);
+  printf(array[1]);
 }
 '
 
+# Confirmation regarding delete option
+if [ "$DELETE" = true ]; then
+  echo "Are you sure you want to delete the unused files?"
+  echo "Type 'yes' to continue: "
+  read answer
+  if [ "$answer" != "yes" ]; then
+    echo "Aborting..."
+      exit 1
+  fi
+fi
+
 for filePath in `find $directoryPath -type f`; do
-    fileName=$(echo $filePath | awk "$splitter")
-    fileExtension=${fileName##*.}
-    fileNameWithoutExtension=${fileName%.*}
+  fileName=$(echo $filePath | awk "$splitter")
+  fileExtension=${fileName##*.}
+  fileNameWithoutExtension=${fileName%.*}
 
-    # If the file is not in the target extensions, skip it
-    if ! [[ "${targetExtensions[@]}" =~ "$fileExtension" ]]; then
-        continue
-    fi
+  # If the file is not in the target extensions, skip it
+  if ! [[ "${TARGET_EXTENSIONS[@]}" =~ "$fileExtension" ]]; then
+    continue
+  fi
 
-    targetFilePaths+=($fileNameWithoutExtension)
-    usingModuleName=$(awk "$moduleNameRetriver" $filePath)
-    usingModulePaths+=($usingModuleName)
+  targetFilePaths+=($fileNameWithoutExtension)
+  usingModuleName=$(awk "$moduleNameRetriver" $filePath)
+  usingModulePaths+=($usingModuleName)
 done
 
 # Remove duplicates
@@ -151,9 +116,9 @@ usingModulePaths=($(echo "${usingModulePaths[@]}" | tr ' ' '\n' | sort -u | tr '
 
 # Store unmatched modules in array
 for targetFilePath in ${targetFilePaths[@]}; do
-    if [[ ! ${usingModulePaths[@]} =~ $targetFilePath ]]; then
-        unusedModulePaths+=($targetFilePath)
-    fi
+  if [[ ! ${usingModulePaths[@]} =~ $targetFilePath ]]; then
+    unusedModulePaths+=($targetFilePath)
+  fi
 done
 
 # Remove duplicates
@@ -161,51 +126,40 @@ unusedModulePaths=($(echo "${unusedModulePaths[@]}" | tr ' ' '\n' | sort -u | tr
 
 # Output absolute paths of unused modules to file
 for filePath in `find $directoryPath -type f`; do
-    fileName=$(echo $filePath | awk "$splitter")
-    fileNameWithoutExtension=${fileName%.*}
+  fileName=$(echo $filePath | awk "$splitter")
+  fileNameWithoutExtension=${fileName%.*}
 
-    # Ignore the target directory
-    for ignoreDirectory in ${IGNORE_DIRS[@]}; do
-        if [[ "$filePath" == *${ignoreDirectory}* ]]; then
-            echo $YELLOW"Skip: $filePath"$NO_COLOR
-            continue 2
-        fi
-    done
-
-    # Ignore defined target files
-    if [[ ${IGNORE_FILES[@]} =~ $fileName ]]; then
-        continue
+  # Ignore the target directory
+  for ignoreDirectory in ${IGNORE_DIRS[@]}; do
+    if [[ "$filePath" == *${ignoreDirectory}* ]]; then
+      echo $YELLOW"Skip: $filePath"$NO_COLOR
+      continue 2
     fi
+  done
 
-    # Ignore the target file specified from the command line.
-    if [[ ${excludeFiles[@]} =~ $fileName ]]; then
-        continue
-    fi
+  # Ignore defined target files
+  if [[ ${IGNORE_FILES[@]} =~ $fileName ]]; then
+    continue
+  fi
 
-    # If the file is in the unused list, delete it
-    for unusedModulePath in ${unusedModulePaths[@]}; do
-        if [[ $fileNameWithoutExtension == $unusedModulePath ]]; then
-            if [ "$fileNameWithoutExtension" != "index" ]; then
-                coloredFileName="${YELLOW}$fileName${NO_COLOR}"
-                coloredFilePath=$(echo "$filePath" | awk -v before=$fileName -v after=$coloredFileName "$replacer")
-
-                # echo $coloredFilePath # for debugging
-                echo $filePath >> $outputFileName
-
-                if [ "$delete" = true ]; then
-                    if [ "$confirm" = true ]; then
-                        clear
-                        echo "Are you sure you want to delete \n\n\t$coloredFilePath?\n"
-                        echo "Type 'yes' to continue: "
-                        read answer
-                        if [ "$answer" = "yes" ]; then
-                            rm $filePath
-                        fi
-                    else
-                        rm $filePath
-                    fi
-                fi
-            fi
+  # If the file is in the unused list, delete it
+  for unusedModulePath in ${unusedModulePaths[@]}; do
+    if [[ $fileNameWithoutExtension == $unusedModulePath ]]; then
+      coloredFileName="${RED}$fileName${NO_COLOR}"
+      filePathWithoutLastChild=$(echo "$filePath" | awk -v file_name=$fileName "$replacer")
+      if [ "$DELETE" = true ]; then
+        if [ "$CONFIRM" = true ]; then
+          clear
+          echo "Are you sure you want to delete \n\n\t$filePathWithoutLastChild$coloredFileName?\n"
+          echo "Type 'y' to continue: "
+          read answer
+          if [ "$answer" = "y" ]; then
+            rm $filePath
+          fi
+        else
+          rm $filePath
         fi
-    done
+      fi
+    fi
+  done
 done
